#!/bin/python

import argparse
from scapy.all import *


class Sniffer:
	def __init__(self,args):
		self.args = args
	def __call__(self,packet):
		if self.args.verbose:
			packet.show()
		else:
			print(packet.summary())

	def run_forever(self):
		packets = sniff(iface=self.args.interface,count=self.args.count)
		return packets
		

if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument('-v','--verbose',default=False, action='store_true', help='verbose output, more information')

	parser.add_argument('-i', '--interface', type=str, required=True, help='network interface name')
	parser.add_argument('-c', '--count', type=int, required=True, help='Number of packets to sniff')
	args = parser.parse_args()
	sniffer = Sniffer(args)

	capture = sniffer.run_forever()
	wrpcap('iot.pcap', capture)

